### PR TITLE
Adding ASOBO proprietary supercompression scheme

### PR DESCRIPTION
**Pull request by JulienVernay-AsoboStudio**
Hello,
This is the patch following up the issue #194 .
I had some trouble with the "icon" causing wrong formatting, so I just dropped it.
Is that correct?

### CODE REVIEW

**Comment by MarkCallow** [comment]
There is no "mail" glyph in Font Awesome hence your troubles with the icon. Use `icon:send` as in the example.

For the benefit of the validator it will be beneficial to state if your scheme needs supercompression global data.  Please add either "n/a" or "Required" in the Global Data Format column.

**Comment by JulienVernay-AsoboStudio** [comment]
Thank you for your feedback.
I was misleaded by GitHub viewer, but with AsciiDoctor it works fine :)

**Comment by MarkCallow** [comment]
I realized there was an error in the table header which likely is the reason you have both level data and global data "link" in the same table cell. I fixed the issues and merged this manually. See 98043e1eca936938159b5be67e7e5855b8d4883b.

Thank you for registering your scheme.

**Comment by JulienVernay-AsoboStudio** [comment]
Thank you!

**Pull request closed without merging**
