### PR TITLE
Add format switches generator

### PR DESCRIPTION
**Pull request by lexaknyazev**
@MarkCallow 
Please suggest a directory for the generated files (it's repo root now) and a URL for the script.

### CODE REVIEW

**Comment by MarkCallow** [comment]
Sorry for the long delay.

I suggest an argument to specify where the generated files should go, defaulting to `out`. I'm not sure what you mean my a URL for the script. Do you mean where to put it in this repo? In the repo root is fine.

**Comment by lexaknyazev** [comment]
> I suggest an argument to specify where the generated files should go, defaulting to `out`.

Done.

**Comment by MarkCallow** [comment]
The generated files look good. I think I now know what "URL for the script refers to." The do-not-edit comment should  have the URL of the script (https://github...) as I anticipate some people running the script from a clone of the KTX-Specification repo and having the output files in a different repo. When people look at those files later, they may need to find the script.

Please add info to the README.md about this script. Basically what it is for and how to run it.

**Comment by lexaknyazev** [comment]
> Please add info to the README.md about this script. Basically what it is for and how to run it.

Done.

**Comment by MarkCallow** [comment]
Since the script has a #! line in it, shouldn't we set the executable permission on the file so you run it just be typing the script name?

**Comment by lexaknyazev** [comment]
Done.

**Comment by MarkCallow** [comment]
Thanks for this.

**Pull request merged**
